// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebnqbrwluyzntclakdqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibnFicndsdXl6bnRjbGFrZHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDg0ODQsImV4cCI6MjA2NTQ4NDQ4NH0.A8iaYqI-tDoADNtOJP7RVj7fOTbvFpg-c5d3Fz4Ze_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);